name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: EmployeeAdminPortal/EmployeeAdminPortal

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: EmployeeAdminPortal/EmployeeAdminPortal

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: EmployeeAdminPortal/EmployeeAdminPortal

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish
      working-directory: EmployeeAdminPortal/EmployeeAdminPortal
